# Generated by Django 6.1.1 on 2026-09-06 15:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('origin_coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('route_geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('departure_time', models.DateTimeField()),
                ('available_seats', models.PositiveSmallIntegerField(default=3)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('stop_order', models.PositiveIntegerField(help_text='Order in the route: 1 for first pickup, 2 for second, etc.')),
                ('price_from_origin', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('trip', 'stop_order')},
            },
        ),
    ]
