# Generated by Django 6.1.1 on 2026-09-06 15:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination_coords',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin_coords',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
